### PR TITLE
Update Autopilot & Hardware codes

### PR DESCRIPTION
**Pull request by Kikobeats**
I removed `hardware` keyword because hardware is a totally different thing; You can have Autopilot 2 with HW2, HW2.5 or HW3.0

### CODE REVIEW

**Comment by timdorr** [comment]
Thanks!

**Comment by timdorr** [comment]
Oops, looks like there are conflicts with your other PR.

**Comment by Kikobeats** [comment]
Hey @timdorr, the conflict is now resolved 🙂

**Comment by timdorr** [comment]
Thanks!

**Pull request merged**
