### PR TITLE
Add upgrade eligibility check 

### PR DESCRIPTION
**Pull request by timdorr**
Redo of #171 by @pdobb, since I mucked things up royally on his PR.

The docs part needs to be updated, as this isn't for software update checking, but for paid upgrades (like Acceleration Boost).

### CODE REVIEW

**Review by liveDC — APPROVED** [review]

**Comment by Abdullaalsuwaidi** [comment]
I need someone to help me to do this Unofficial API please here is my discord! GrandpaRage#0188 
I really need help also thanks!

**Comment by Abdullaalsuwaidi** [comment]
I need help in this API it doesnt work can someone teach me?

**Comment by BradenM** [comment]
Hi @timdorr @pdobb, 

I stumbled across this PR while just exploring the API and its capabilities (thank you @timdorr for the fantastic resource!). 

Anyways, I gave this endpoint a try and received a slightly different response that I have not seen mentioned yet. Figured I'd point it out:

```
{
    "safety_metrics_eligible": false,
    "upgrade_eligible": false
}
```
Has anyone else seen this "safety_metrics_eligible" field before?

For reference, the target vehicle is a 2022 Model 3 AWD with:
- FSD purchased + _enrolled_ in beta, but _not_ currently active
- Accel boost _not_ purchased, but is listed as an option under upgrades.
- `vehicle_data` endpoint reports `api_version` 44 and `car_version` `2022.24.5 2492cccee5b4`

Based on https://github.com/timdorr/tesla-api/pull/171#issuecomment-570584403, I wonder if the field refers to whether the vehicle is eligible for FSD beta based on the current safety score. My score is currently a 90, which would fall below the (suspected) minimum of ~95 for FSD eligibility. Any thoughts?

**Comment by metarom** [comment]
Hi, is it possible to add "media_info": {
          "a2dp_source_name": "iPhone",
          "audio_volume": 2.0,
          "audio_volume_increment": 0.333333,
          "audio_volume_max": 10.333333,
          "media_playback_status": "Stopped",
          "now_playing_album": "",
          "now_playing_artist": "",
          "now_playing_duration": 0,
          "now_playing_elapsed": 0,
          "now_playing_source": "TuneIn",
          "now_playing_station": "",
          "now_playing_title": ""

to /api/1/vehicles/{id}/vehicle_data, currently only seeing this data in legacy request

**Pull request closed without merging**
