### PR TITLE
Document vault_profile partially

### PR DESCRIPTION
**Pull request by ArchGryphon9362**

### CODE REVIEW

**Comment by core-hacked** [comment]
Hi, could you also document Vault profile deletion?
I though of doing it myself as mentioned in #732  but haven't had the time recently. Would be greatly appreciated!
```json
"USER_RESET_VAULT": {
    "TYPE": "DELETE",
    "URI": "api/1/users/vault_profile",
    "AUTH": true
  },
  ```

**Comment by ArchGryphon9362** [comment]
Will do in a couple hours :) (does it literally just clear the vault I assume? any consequences? or you don't know? if so, can check myself)

**Comment by timdorr** [comment]
My guess is this is for CarKey and the Android equivalent. Both rely on their own Wallet implementation, which is all about key exchange and storage, which is what this API is all about. I don't have the spec handy, but I'm guessing they're [following CCC's standard](https://carconnectivity.org/).

**Comment by ArchGryphon9362** [comment]
Just requested the spec, and it doesn’t mention the word vault not a single time. And plus - this vault is device wide. If this is possibly even for CarKey, I’d guess that it isn’t directly related.

**Comment by timdorr** [comment]
It's not about having a "vault" or other kinds of centralized key storage, it's about key exchange with the car for the purposes of opening the vehicle. The storage mechanism for those keys is opaque to the spec. It's about what you do with the keys, which this seems to indicate (hence the `ActiveVaultReason` enum).

Anyways, this looks good. Thanks!

**Comment by core-hacked** [comment]
> It's not about having a "vault" or other kinds of centralized key storage, it's about key exchange with the car for the purposes of opening the vehicle. The storage mechanism for those keys is opaque to the spec. It's about what you do with the keys, which this seems to indicate (hence the `ActiveVaultReason` enum).
> 
> 
> 
> Anyways, this looks good. Thanks!

Good guesses but I think this is just the Reset Tesla Profile button

image

**Pull request merged**
