### PR TITLE
Update data request responses

### PR DESCRIPTION
**Pull request by jor-dan**

### CODE REVIEW

**Comment by timdorr** [comment]
I just got 2019.40.2.1, so let me see if there is any other new keys in there and then I'll merge this in. Thanks!

**Comment by davidhodge** [comment]
Am curious if you have an automated check for new keys! If so, how are you doing that?  (if you don't mind me asking.)

**Comment by jor-dan** [comment]
> Am curious if you have an automated check for new keys! If so, how are you doing that? (if you don't mind me asking.)

No, I just manually check, but there aren't that many fields so it isn't much trouble. Automating it is an interesting idea... Some fields only appear under certain circumstances though.

**Comment by timdorr** [comment]
Yeah, there are differences between all the models, even the sub-models and configurations (Model S with MCU1 + AP2.0 has different data from a Model 3). But there are plenty of common keys to document.

**Comment by timdorr** [comment]
Yep, good thing I checked. The api_version has bumped to 7 in 2019.40.2.1, so there are some updates. I'll merge this in since I can't edit it directly, and then add those on master. Thanks again!

**Pull request merged**
