### PR TITLE
Add upgrade eligibility check

### PR DESCRIPTION
**Pull request by pdobb**
Add TeslaApi::Vehicle#upgrade_eligible?, which is assumed to be used for checking if a software upgrade is available for the queried vehicle.

I also updated the docs for this method. Although, I'm not 100% sure my assumptions on this method are correct yet. I will test once my car indicates that it has a software update available (which should be soon).

## Note: Help needed!
I didn't add 
- spec/cassettes/vehicle-no_upgrade_eligible.yml
- spec/cassettes/vehicle-upgrade_eligible.yml

because I'm unwilling to add my vehicle data to the source repo. So these will need to be generated and then `spec/cassettes/vehicle-upgrade_eligible.yml` will need to be manually altered to:
```ruby
body:
  encoding: UTF-8
  string: '{"upgrade_eligible":true}'
```
in order for the test suite to pass.

I looked into filtering sensitive data from the VCR cassettes, but was disappointed to find that it doesn't accept regexes. I started to go down the "manual" filtering path by adding e.g.

```ruby
c.filter_sensitive_data('<VIN>') { ENV['TESLA_VIN'] }
```
to spec/spec_helper.rb, and that works but ads yet another ENV var to keep track of and doesn't filter out enough personal identifying info for my taste still.

### CODE REVIEW

**Comment by jor-dan** [comment]
> ... which is assumed to be used for checking if a software upgrade is available for the queried vehicle.
> Although, I'm not 100% sure my assumptions on this method are correct yet. I will test once my car indicates that it has a software update available (which should be soon).

I might be misinterpreting this but are you mixing up paid software upgrades (FSD, Acceleration Boost) with free vehicle software updates? Due to some reasons I'm pretty sure this endpoint is related to paid upgrades so unless you're waiting for an upgrade you purchased it shouldn't change.

This endpoint used to return a response with a key called `autopilot` that's now been renamed to `upgrade_eligible`. It was added (#135) with an endpoint named `AUTOPILOT_UPGRADE_URL` that was later (#161) shortened to just `UPGRADE_URL` a few weeks prior to the release of the Acceleration Boost paid upgrade.

The `vehicle_state` request's response also already provides information about the status of regular software updates, but not paid software upgrades which would lead me to believe this newer endpoint is for the latter.

**Comment by timdorr** [comment]
Yeah, that's correct. I have this set to true on my vehicle, but it's a Model S and is for the FSD upgrade. 

I can create the cassettes when I get to a computer.

**Comment by jor-dan** [comment]
> I have this set to true on my vehicle, but it's a Model S and is for the FSD upgrade.

I get a false response but have FSD in the eligible upgrades section of the app.

**Comment by timdorr** [comment]
Huh, yeah, mine switched over to false too.

**Comment by timdorr** [comment]
@pdobb Can you please set this branch to accept edits from contributors? I can add the cassettes that way.

**Comment by pdobb** [comment]
@timdorr I think it is set:
image
Is there somewhere else to check?

**Comment by pdobb** [comment]
@jor-dan I very well may be getting this confused as I'm new here :). Thanks for the insight. I'll double check once my car is eligible for 40.50.7 and report back.

**Comment by timdorr** [comment]
Uh, that's not what was supposed to happen...

**Comment by timdorr** [comment]
Well, I don't know what I did exactly. I've never had a non-ff issue with PRs before. But my force push seems to have replaced the contents (I messed that up, for sure) and now I don't have permissions because this is closed out...

I pushed the contents to the pdobb-master branch here. You can use that to pull in those changes and put them back on your master branch. Really sorry about the hassle!

**Comment by pdobb** [comment]
If you have the code, feel free to just take it over. Or I can re-open a PR. I think I got the setting assumptions wrong anyway and it probably won't be a boolean in the end...

**Comment by kevykk** [comment]
Having issues with the window venting command and sentry mode setting. 1) The commands go in the query params, right, not the header or body? 2) How did you check the stream of data to and from the Tesla app? Is there a way to view the Tesla app's actual command data sent? Thanks.

**Pull request closed without merging**
